### ISSUE TITLE
Problem ‘invalid param 4: unknown type 11 ‘ should be fix.

### ISSUE THREAD

**Issue by drscrewdriver** [maikelwever/lxd#17]
You may know  Current version seems to fail container creation with Failed container creation: invalid param 4: unknown type 11 
Change version to pkgbuild file lead to same problem 3.4 3.0 
Is there problem with the dqlite?

**Comment by taketi32** [comment]
Hello, you can temporarily fix the problem by installing the git version of dqlite-git. It worked for me.

- https://aur.archlinux.org/packages/dqlite-git/

**Comment by maikelwever** [comment]
New version builds dqlite inline avoiding all these issues.
